---
title: "Portfolio optimazation (data driven)"
author: "Zimo"
date: "2019.09.09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading Package and Download Data
```{r}
rm(list=ls())
library(zoo)
library(tseries)
library(corrplot)
library(xts)
library(xtable)
dateStart <- "2002-01-01"               
dateEnd <- "2019-7-31"
###### online service
Amazon <- get.hist.quote(instrument="AMZN",start = dateStart,end=dateEnd,quote = c("AdjClose"),
                       retclass="zoo")
# World Wresting Entertainment 
#### Entertainment
WWE<-get.hist.quote(instrument="WWE",start = dateStart,end=dateEnd,quote = c("AdjClose"),
                      retclass="zoo")
#### Information Technology
MSFT<-get.hist.quote(instrument="msft",start = dateStart,end=dateEnd,quote =
                       c("AdjClose"),retclass="zoo")
### Pepsi
#### food
PEP<-get.hist.quote(instrument="PEP",start = dateStart,end=dateEnd,quote =
                       c("AdjClose"),retclass="zoo")
##### I will use the dataset in total, but here I only use the last 1500 values
data<-merge(Amazon, WWE, MSFT, PEP) 
### four companies comes from four different industries
data<-as.matrix(data)
colnames(data)<-c("Amazon", "WWE", "MSFT", "PEPSI")
prices<-tail(data, 1501)
#rownames(prices)
n = dim(prices)[1]
##### caculating returns for 1500 values
R =  (prices[2:n, ] / prices[1:(n-1), ] - 1)
number=ncol(data)
#index(data)
```
Download risk-free rate
```{r}
#### data on risk-free asset
Rf<-read.csv("TB3MS.csv")
mufree<-as.numeric(tail(Rf, 1)[2]/(63*100))
```

```{r}
#### caculate the lag 1 acf of return, absolute value of return and square return
acf.R<-matrix(0, nrow=number, ncol=3)
for(j in 1:number){
  acf.R[j, ]<-c(acf(R[, j], plot=FALSE)$acf[2],
                acf(abs(R[, j]), plot=FALSE)$acf[2],
                acf(R[, j]^2, plot=FALSE)$acf[2])
  ###### acf[2] means lag 1 sample auto-correlation
}
rownames(acf.R)<-colnames(R)
colnames(acf.R)<-c("series", "abs", "sq")
acf.R
xtable(acf.R, digits=4)
```

```{r}
rho<-rep(0, number)
for(j in 1:number){
  rho[j]<-cor(R[, j]-mean(R[, j]), sign(R[, j]-mean(R[, j])))
}
names(rho)<-colnames(data)
rho
nu<-rep(0, number)
for(j in 1:number){
  fun <- function (x) rho[j]*(x-1)*beta(x/2,1/2)-2*sqrt(x-2)
  nu[j] <- uniroot(fun, c(2, 8))$root
}
nu
```

Empirical:
```{r}
mean_vect = apply(R,2,mean)
cov_mat<-cov(R)
z<-solve(cov_mat)%*%(mean_vect-mufree)
w.sigma.emp<-z/sum(z)
w.sigma.emp
```

Data Driven:
```{r}
#### choosing optimal alpha for EWMA
dd.alpha<-function(Z){
  alpha<-seq(0.01, 0.3, 0.01)
  t<-length(Z)
  cut.t<-200
  MSE_alpha<-rep(0, length(alpha))
  for(a in 1:length(alpha)){
    s<-mean(Z[1:cut.t])
    error<-rep(0, t)
    for(i in 1:t){
      error[i]<-Z[i]-s
      s<-alpha[a]*Z[i]+(1-alpha[a])*s
    }
    MSE_alpha[a]<-mean(error[-(1:cut.t)]^2)
  }
  alpha.opt<-alpha[which.min(MSE_alpha)]
  return(alpha.opt)
}
```

```{r}
#### data driven method to forecast volatility
dd.vol<-function(y){
  t<-length(y)
  rho<-cor(y-mean(y), sign(y-mean(y)))
  vol<-abs(y-mean(y))/rho
  alpha<-dd.alpha(vol)
  cut.t<-500
  s<-mean(vol[1:cut.t])
  for(i in 1:t){
    s<-alpha*vol[i]+(1-alpha)*s
  }
  return(s)
}
```

```{r}
#### data driven approach to caculate residuals
dd.res<-function(y){
  rho<-cor(y-mean(y), sign(y-mean(y)))
  vol<-abs(y-mean(y))/rho
  alpha<-dd.alpha(vol)
  cut.t<-500
  s<-mean(vol[1:cut.t])
  t<-length(y)
  res<-y
  for(i in 1:t){
    res[i]<-(y[i]-mean(y))/s
    s<-alpha*vol[i]+(1-alpha)*s
  }
  return(res)
}
```

```{r}
dd.cor.mat<-function(R){
  R.res<-R
  for(j in 1:ncol(R)){
    R.res[, j]<-dd.res(R[, j])
  }
  cor_mat<-cor(R.res)
  return(cor_mat)
}
```

```{r}
dd<-function(y){
  alpha<-seq(0.01, 0.3, 0.01)
  t<-length(y)
  cut.t<-500 
  rho<-cor(y-mean(y), sign(y-mean(y)))
  vol<-abs(y-mean(y))/rho
  MSE_alpha<-rep(0, length(alpha))
  sn<-rep(0, length(alpha))
  for(a in 1:length(alpha)){
    s<-mean(vol[1:cut.t])
    error<-rep(0, t)
    for(i in 1:t){
      error[i]<-vol[i]-s
      s<-alpha[a]*vol[i]+(1-alpha[a])*s
    }
    MSE_alpha[a]<-mean(error[-(1:cut.t)]^2)
    sn[a]<-s
  }
  vol.fore<-sn[which.min(MSE_alpha)]
  return(vol.fore)
}
```

```{r}
mean_vect = apply(R,2,mean)
cor_mat<-dd.cor.mat(R)
sd_vect<-apply(R, 2, dd)
cov_mat<-sd_vect%*%t(sd_vect)*cor_mat
z<-solve(cov_mat)%*%(mean_vect-mufree)
w.sigma.dd<-z/sum(z)
cor_mat.dd<-cor_mat
cov_mat.dd<-cov_mat
```

```{r}
portfolio_returns = function(w, asset_returns) {
  port.returns = 0
  
  # Multiplication of the i-th asset by the i-th weight in "x"
  for (i in 1:length(w)) {
    port.returns = port.returns + asset_returns[,i] * w[i]
  }
  
  return (port.returns)
}
```

```{r}
w.sigma<-data.frame(w.sigma.dd, w.sigma.emp, diag(1, number))
colnames(w.sigma)<-c("DD", "EMP", colnames(data))
w.sigma
sharpe.ratio<-c()
for(j in 1:ncol(w.sigma)){
  w<-w.sigma[, j]
  R.port<-portfolio_returns(w, R)
  vol<-dd(R.port)
  sharpe.ratio[j]<-(mean(R.port)-mufree)/vol
}
names(sharpe.ratio)<-c("DD", "EMP", colnames(data))
sharpe.ratio
```

```{r}
corrplot(cor(R), method="ellipse", main="Empirical")
corrplot(cor_mat.dd, method="ellipse", main="Data Driven")
cor(R); cor_mat.dd
cov(R); cov_mat.dd
```

Caculating sign-correlation and degree of freedom
```{r}
rho.cal<-function(R){
  rho<-cor(R-mean(R), sign(R-mean(R)))
  return(rho)
}
nu.cal<-function(R){
  rho<-cor(R-mean(R), sign(R-mean(R)))
  fun <- function (x) rho*(x-1)*beta(x/2,1/2)-2*sqrt(x-2)
  nu <- uniroot(fun, c(2, 8))$root
  return(nu)
}
```

```{r caculate portfolio returns and sign-rho, and degree of freedom}
#### caculate the portfolio returns
R.port<-R%*%as.matrix(w.sigma)
rho<-apply(R.port, 2, rho.cal)
rho
nu<-apply(R.port, 2, nu.cal)
nu
```

VaR and ES caculation:
```{r}
#### forecasting volatility based on data driven method
vol.port<-apply(R.port, 2, dd)
#### caculating VaR
VaR.port<-(-1000)*qt(0.01, df=nu)*sqrt((nu-2)/nu)*vol
VaR.port
#### caculating ES
ES.cal<-function(nu, p) sqrt((nu-2)/nu)*dt(qt (p,nu), nu)/p*(nu + (qt (p,nu))^2)/(nu-1)
ES.port<-VaR.port
for(j in 1:number){
  ES.port[j]<-vol.port[j]*1000*ES.cal(nu[j], 0.01)
}
ES.port
```

```{r}
#### summarize the portfolio and individual stock
portfolio<-data.frame(sharpe.ratio,rho, nu, VaR.port, ES.port )
colnames(portfolio)<-c("Sharpe Ratio","rho", "df", "VaR", "ES")
portfolio
xtable(portfolio, digits=4)
```

Rolling:
```{r}
sharpe.emp.cal<-function(R, mufree){
  #mufree=0
  mean_vect = apply(R,2,mean)
  cov_mat<-cov(R)
  z<-solve(cov_mat)%*%(mean_vect-mufree)
  w<-z/sum(z)
  R.port<-portfolio_returns(w, R)
  vol<-dd(R.port)
  mad<-vol*cor(R.port-mean(R.port), sign(R.port-mean(R.port)))
  #sharpe.ma<-(mean(R.port)-mufree)/vol
  nu<-nu.cal(R.port)
  return(c(mean(R.port), vol, nu, mad))
}
```

```{r}
sharpe.dd.cal<-function(R, mufree){
  mean_vect = apply(R,2,mean)
  cor_mat<-dd.cor.mat(R)
  sd_vect<-apply(R, 2, dd)
  cov_mat<-sd_vect%*%t(sd_vect)*cor_mat
  if(prod(eigen(cov_mat)$value>=0)==1) print("positive definite")
  else print("negative definite")
  #mufree=0
  z<-solve(cov_mat)%*%(mean_vect-mufree)
  w<-z/sum(z)
  R.port<-portfolio_returns(w, R)
  vol<-dd(R.port)
  #sharpe.dd<-(mean(R.port)-mufree)/vol
  nu<-nu.cal(R.port)
  mad<-vol*cor(R.port-mean(R.port), sign(R.port-mean(R.port)))
  return(c(mean(R.port), vol, nu, mad))
}
```

```{r}
month.date<-c("2017-08", "2017-09", "2017-10", "2017-11", "2017-12",
              "2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06",
              "2018-07", "2018-08", "2018-09", "2018-10", "2018-11", "2018-12",
              "2019-01", "2019-02", "2019-03", "2019-04", "2019-05", "2019-06",
              "2019-07")
R<-as.xts(R)[month.date]
end.names<-rownames(as.matrix(R))
end.names<-tail(end.names, 250)
mufree<-Rf[, 2]
names(mufree)<-Rf$DATE
mufree<-as.xts(mufree)[month.date]
risk.free<-R[, 1]
for(i in 1:length(month.date)){
  risk.free[month.date[i]]<-mufree[month.date[i]]
}
mufree<-as.vector(risk.free)/(100*65)
mufree<-tail(mufree, 250)
colnames(mufree)<-NULL
prices<-tail(data, 1501+length(mufree))
rownames(prices)[1]
n = dim(prices)[1]
R =  (prices[2:n, ] / prices[1:(n-1), ] - 1)
#number=ncol(data)
summary.emp<-matrix(0, nrow=length(mufree), ncol=4)
summary.dd<-matrix(0, nrow=length(mufree), ncol=4)
for(i in 1:length(mufree)){
  R.use<-as.data.frame(R[i:(1500+i-1), ])
  summary.emp[i, ]<-sharpe.emp.cal(R.use, mufree[i])
  summary.dd[i, ]<-sharpe.dd.cal(R.use, mufree[i])
}
```

```{r}
mean.port<-data.frame(summary.emp[,1], summary.dd[, 1])
vol.port<-data.frame(summary.emp[, 2], summary.dd[, 2])
nu.port<-data.frame(summary.emp[, 3], summary.dd[, 3])
sharpe.port<-data.frame((mean.port[, 1]-mufree)/vol.port[, 1], 
                        (mean.port[, 2]-mufree)/vol.port[, 2])
mad.port<-data.frame(summary.emp[, 4], summary.dd[, 4])
colnames(mean.port)<-c("emp", "dd")
rownames(mean.port)<-end.names
colnames(vol.port)<-c("emp", "dd")
rownames(vol.port)<-end.names
colnames(nu.port)<-c("emp", "dd")
rownames(nu.port)<-end.names
colnames(sharpe.port)<-c("emp", "dd")
rownames(sharpe.port)<-end.names
colnames(mad.port)<-c("emp", "dd")
rownames(mad.port)<-end.names
mean.port; vol.port; nu.port
#### sd of mean of portfolio
mean_sd<-apply(mean.port, 2, sd)
mean_sd
```

```{r}
VaR.port.dd<-(-1000)*(mean.port[, 2]+vol.port[, 2]*sqrt((nu.port[, 2]-2)/nu.port[, 2])*
                        qt(0.01, df=nu.port[, 2]))
VaR.port.emp<-(-1000)*(mean.port[, 1]+vol.port[, 1]*sqrt((nu.port[, 1]-2)/nu.port[, 1])*
                        qt(0.01, df=nu.port[, 1]))
ES.port.dd<-VaR.port.dd
ES.port.emp<-VaR.port.emp
for(i in 1:length(VaR.port.dd)){
  ES.port.dd[i]<-ES.cal(nu.port[i, 2], 0.01)*1000*vol.port[i, 2]
  ES.port.emp[i]<-ES.cal(nu.port[i, 1], 0.01)*1000*vol.port[i, 1]
}
VaR.port<-data.frame(VaR.port.emp, VaR.port.dd)
ES.port<-data.frame(ES.port.emp, ES.port.dd)
rownames(VaR.port)<-end.names
rownames(ES.port)<-end.names
colnames(VaR.port)<-c("emp", "dd")
colnames(ES.port)<-c("emp", "dd")
VaR.port; ES.port
```

```{r}
hist(sharpe.port[, 1], main="EMPIRICAL")
hist(sharpe.port[, 2], main="Data Driven")
```

```{r}
plot(as.xts(sharpe.port), type="l", main="Sharpe ratio forecast of the portfolio",
     ylim=c(min(sharpe.port), max(sharpe.port)),col=c("blue", "red"))
addLegend("topright", on=1, 
          legend.names = c("EMP", "DD"), 
          lty=c(1, 1), lwd=c(1, 1),
          col=c("blue", "red"))

plot(as.xts(VaR.port), type="l", main="VaR forecast of the portfolio",
     ylim=c(min(VaR.port), max(VaR.port)+20),col=c("blue", "red"))
addLegend("topright", on=1, 
          legend.names = c("EMP", "DD"), 
          lty=c(1, 1), lwd=c(3, 3),
          col=c("blue", "red"))

plot(as.xts(ES.port), type="l", main="ES forecasts of the portfolios",
     ylim=c(min(ES.port), max(ES.port)),col=c("blue", "red"))
addLegend("topright", on=1, 
          legend.names = c("EMP", "DD"), 
          lty=c(1, 1), lwd=c(1, 1),
          col=c("blue", "red"))

plot(as.xts(vol.port), type="l", main="Volatility forecasts of the portfolios",
     ylim=c(min(vol.port), max(vol.port)+0.01),col=c("blue", "red"))
addLegend("topright", on=1, 
          legend.names = c("EMP", "DD"), 
          lty=c(1, 1), lwd=c(3, 3),
          col=c("blue", "red"))

plot(as.xts(mad.port), type="l", main="Mad forecasts of the portfolios",
     ylim=c(min(mad.port), max(mad.port)+0.01),col=c("blue", "red"))
addLegend("topright", on=1, 
          legend.names = c("EMP", "DD"), 
          lty=c(1, 1), lwd=c(3, 3),
          col=c("blue", "red"))
sharpe.ratio.mean<-apply(sharpe.port, 2, mean)
sharpe.ratio.sd<-apply(sharpe.port, 2, sd)
VaR.mean<-apply(VaR.port, 2, mean)
VaR.sd<-apply(VaR.port, 2, sd)
ES.mean<-apply(ES.port, 2, mean)
ES.sd<-apply(ES.port, 2, sd)
mad.sd<-apply(mad.port, 2, sd)
vol.sd<-apply(vol.port, 2, sd)
sharpe.ratio.mean; sharpe.ratio.sd
sharpe.summary<-data.frame(sharpe.ratio.mean, sharpe.ratio.sd)
                          
                           #mad.sd,VaR.sd,ES.sd)
xtable(sharpe.summary, digits=4)

risk.summary<-data.frame(vol.sd, mad.sd,VaR.sd,ES.sd)
xtable(risk.summary, digits=4)
```

```{r}
utility<-(sharpe.port[, 2]^2-sharpe.port[, 1]^2)/(sharpe.port[, 1]^2)*100
mean(utility)
utility<-as.data.frame(utility)
#colnames(utility)<-"% change in utility"
library(ggplot2)
ggplot(utility, aes(x=utility))+
  geom_histogram(color="darkblue", fill="lightblue", binwidth = 20)+
  geom_vline(aes(xintercept=mean(utility)),
             color="red", linetype="dashed", size=1)+
  labs(title="% change in utility histogram plot",x="% change in Utility")
  
```

```{r}
library(ggplot2)
meth.name<-c(rep("EMP", nrow(vol.port)),
             rep("DD", nrow(vol.port)))
data.plot<-data.frame(mad=c(mad.port[, 1], mad.port[, 2]),
                      vol=c(vol.port[, 1], vol.port[, 2]),
                      VaR=c(VaR.port[, 1], VaR.port[, 2]), 
                      ES=c(ES.port[, 1], ES.port[, 2]),
                      meth.name)
par(mfrow=c(4, 1))
ggplot(data.plot, aes(x=meth.name, y=mad, fill=meth.name))+
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=TRUE)
ggplot(data.plot, aes(x=meth.name, y=vol, fill=meth.name))+
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=TRUE)
ggplot(data.plot, aes(x=meth.name, y=VaR, fill=meth.name))+
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=TRUE)
ggplot(data.plot, aes(x=meth.name, y=ES, fill=meth.name))+
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=TRUE)

#vol.p
```


